apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  password: ${K8S_SECRET_BASE64_MYSQL_PASSWORD}
  root_password: ${K8S_SECRET_BASE64_MYSQL_ROOT_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: php-laravel
type: Opaque
data:
  encryption_key: ${K8S_SECRET_BASE64_LARAVEL_ENCRYPTION_KEY}
  license_key: ${K8S_SECRET_BASE64_NEW_RELIC_LICENSE_KEY}
